# Generated by Django 4.2 on 2023-05-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('uasg', models.IntegerField()),
                ('item', models.CharField(max_length=30)),
                ('cliente', models.CharField(max_length=50)),
                ('ganhou', models.BooleanField()),
                ('data_pregao', models.DateField()),
                ('data_entrega', models.DateField()),
            ],
        ),
    ]
