# Generated by Django 4.2 on 2023-05-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitagil', '0003_rename_tipo_tipo_compra_tipo_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacao',
            name='documentos',
            field=models.CharField(max_length=200),
        ),
    ]
