# Generated by Django 4.2 on 2023-06-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licitagil', '0004_alter_licitacao_documentos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licitacao',
            options={'ordering': ['-data_disputa']},
        ),
    ]
